name: CI/CD pipeline to Docker hub and azure web app

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  AZURE_WEBAPP_NAME: your-webapp-name

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push the docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/imsmgmtsystem:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/imsmgmtsystem:${{ github.sha }} 

  deploy:
    needs: build
    runs-on: [ubuntu-latest]
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps: 
      - name: Deploy to azure app
        uses: azure/webapps-deploy@v2

        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ secrets.DOCKER_USERNAME }}/hello-devops:${{ github.sha }}'

